### ISSUE TITLE
url bar does not use browser density

### ISSUE THREAD

**Issue by yant0** [Dinno-DEV/zen-cleaned-url-bar#1]
right click top bar > customize toolbar > density

**Comment by Dinno-DEV** [comment]
Does this fix the issue? If yes I will create a PR to the theme store. Thank you!
![image](https://github.com/user-attachments/assets/7328af57-6a7c-4334-8d57-dcf99306ef7e)
![image](https://github.com/user-attachments/assets/689e8884-78c3-4e72-b8f0-0e3e6f57a6e2)
![image](https://github.com/user-attachments/assets/14c210a4-3f0c-4310-ab82-099fb37d0888)
![image](https://github.com/user-attachments/assets/68ac9635-0019-4fd6-b50e-cddd78534eb1)
![image](https://github.com/user-attachments/assets/a3313c86-6ef0-47b2-9689-52dab2ad053d)
![image](https://github.com/user-attachments/assets/2bdd13f4-bc69-4b3e-ae88-c584d00ba8e6)
