### ISSUE TITLE
Shield icon is not properly aligned

### ISSUE THREAD

**Issue by umarhamzy** [Dinno-DEV/zen-cleaned-url-bar#2]
Love the look of your theme. My only pet peeve is the misaligned shield icon in the URL bar. It's slightly below the rest of the icons when it's not in focus, when it's in focus-- it's way off.

![image](https://github.com/user-attachments/assets/d956e055-6ead-4696-81b2-ab4964acce78)

![image](https://github.com/user-attachments/assets/1919f75f-9640-4750-956f-29131d898b1d)

**Comment by Dinno-DEV** [comment]
Is this fixed now? This is the current pull request that I've been waiting for to be pulled

![image](https://github.com/user-attachments/assets/78d25713-de66-4cc6-a668-bceae7645dc0)
![image](https://github.com/user-attachments/assets/96126c46-f198-4cbb-9453-86a648c5316b)

**Comment by umarhamzy** [comment]
Yup, that's it!
