### ISSUE TITLE
Blur effect lost on none-about:xxx page

### ISSUE THREAD

**Issue by lamteteeow** [Dinno-DEV/zen-cleaned-url-bar#6]
After new update 1.0.1-a20, blur effect seems not to work consistantly on none-about:xxx pages

https://github.com/user-attachments/assets/38b9b48f-8f6b-413c-af5e-aea4a8ba07f2

**Comment by Dinno-DEV** [comment]
Yes, starting from a20, the blur sadly won't work anymore until indefinite time. The blur relies on the browser allowing that to happen, so I can't really do anything about it. Sorry 🙏 I've created a PR that makes the URL bar use the default color.

**Comment by lamteteeow** [comment]
> Yes, starting from a20, the blur sadly won't work anymore until indefinite time. The blur relies on the browser allowing that to happen, so I can't really do anything about it. Sorry 🙏 I've created a PR that makes the URL bar use the default color.

Thanks for swift reply. Love the mod though. Hope to be able to use it again some day :D
